### ISSUE TITLE
Unable to import in newest versions of CrowdAnki / Anki

### ISSUE THREAD

**Issue by jesselatimer** [stephenmaturin/Pathfinder_2#1]
Unable to import on the latest version of CrowdAnki (which in theory supports the latest stable version of Anki, 2.1.40).

Skimming through the recent commits and issues on CrowdAnki, I suspect the cause might be changes in the export process. If this is the case, it may be enough to re-export this deck.

Here is the error message I get, mostly for posterity.

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.14.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-11 08:44:33
Add-ons possibly involved: ⁨CrowdAnki JSON exportimport Edit history Collaborate on deck creation⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/jesselatimer/Library/Application Support/Anki2/addons21/1788670778/anki/ui/action_vendor.py", line 31, in <lambda>
    lambda: AnkiJsonImporter.import_deck(self.window.col, self.directory_vendor))
  File "/Users/jesselatimer/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 112, in import_deck
    AnkiJsonImporter.import_deck_from_path(collection, Path(directory_path))
  File "/Users/jesselatimer/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 101, in import_deck_from_path
    if importer.load_deck(directory_path):
  File "/Users/jesselatimer/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 36, in load_deck
    aqt.mw.backup()
  File "aqt/main.py", line 588, in backup
AssertionError
```

If it turns out re-exporting from the latest version of CrowdAnki doesn't fix the import issue, I'll raise on issue on that repo.

**Comment by Sinled** [comment]
@jesselatimer have you solved this problem?
